[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "=1.13.0"
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
futures-timer = "3.0.3"
